[package]
name = "infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "基础设施层，提供跨领域的基础设施能力"

[dependencies]
client.workspace = true
toolkit.workspace = true
di.workspace = true
reqwest = { workspace = true, default-features = false, features = ["json", "blocking", "multipart", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
rand.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
