# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class Workflow < Formula
  desc "Workflow CLI tool for PR management, Jira integration, and log processing"
  homepage "https://github.com/zevwings/workflow.rs"
  version "0.0.1"
  license "MIT"

  # 从源码构建（使用 git tag）
  depends_on "rust" => :build

  on_macos do
    # 使用 git 仓库和 tag（会自动更新为最新的 tag）
    url "https://github.com/zevwings/workflow.rs.git", tag: "v0.0.1"
  end

  def install
    # 设置环境变量以优化编译过程
    ENV["CARGO_TERM_COLOR"] = "always"
    ENV["CARGO_BUILD_JOBS"] = ENV.fetch("HOMEBREW_MAKE_JOBS", "4").to_s

    # 显示编译进度
    ohai "Building workflow CLI (this may take a few minutes)..."
    ohai "Downloading and compiling dependencies..."

    # 构建所有二进制文件（包括 install，虽然它不会被安装到系统）
    # 使用 --verbose 显示更多输出，让用户知道进度
    system "cargo", "build", "--release", "--verbose", "--bin", "workflow", "--bin", "pr", "--bin", "qk", "--bin", "install"

    ohai "Build completed! Installing binaries..."

    # 只安装用户可用的命令到系统
    bin.install "target/release/workflow"
    bin.install "target/release/pr"
    bin.install "target/release/qk"

    # 临时安装 install 二进制文件，用于 post_install 中的 completion 安装
    # 安装后会被保留，用户可以使用它来安装 completions
    bin.install "target/release/install"
  end

  def post_install
    # 创建符号链接到 /usr/local/bin（如果目录存在且可写）
    local_bin = "/usr/local/bin"
    homebrew_prefix = ENV.fetch("HOMEBREW_PREFIX", "/opt/homebrew")

    if Dir.exist?(local_bin) && File.writable?(local_bin)
      %w[workflow pr qk].each do |cmd|
        source = "#{homebrew_prefix}/bin/#{cmd}"
        target = "#{local_bin}/#{cmd}"
        if File.exist?(source)
          begin
            FileUtils.ln_sf(source, target)
            ohai "Created symlink: #{target} -> #{source}"
          rescue => e
            opoo "Failed to create symlink #{target}: #{e.message}"
            opoo "You may need to run manually: sudo ln -sf #{source} #{target}"
          end
        end
      end
    else
      opoo "/usr/local/bin is not writable. Creating symlinks requires sudo:"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/workflow /usr/local/bin/workflow"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/pr /usr/local/bin/pr"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/qk /usr/local/bin/qk"
    end

    # 自动安装 shell completion
    # 使用已安装的 install 二进制文件来安装 completions
    install_binary = bin/"install"

    if install_binary.exist? && install_binary.executable?
      # 确保环境变量正确设置
      home_dir = ENV.fetch("HOME", Dir.home)
      shell_env = ENV.fetch("SHELL", "/bin/zsh")

      ohai "Installing shell completions..."
      ohai "Using HOME: #{home_dir}"
      ohai "Using SHELL: #{shell_env}"

      # 运行 install 命令来安装 completions
      # 使用 system 命令，但捕获错误并提供更好的反馈
      result = system(install_binary.to_s)

      if result
        ohai "Shell completions installed successfully"
        ohai "To activate completions, run: source ~/.zshrc  # or ~/.bashrc"
      else
        exit_code = $?.exitstatus || 1
        opoo "Failed to install shell completions (exit code: #{exit_code})"
        opoo "You can manually install completions by running:"
        opoo "  #{bin}/install"
        opoo "Or use the workflow command:"
        opoo "  workflow install"
      end
    else
      opoo "Install binary not found at #{install_binary}"
      opoo "Skipping automatic completion installation"
      opoo "You can manually install completions later by running:"
      opoo "  workflow install"
    end
  end

  test do
    system "#{bin}/workflow", "--help"
    system "#{bin}/pr", "--help"
    system "#{bin}/qk", "--help"
  end
end

