# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class Workflow < Formula
  desc "Workflow CLI tool for PR management, Jira integration, and log processing"
  homepage "https://github.com/zevwings/workflow.rs"
  version "0.1.0"
  license "MIT"

  # 方式一：从源码构建（推荐用于开发阶段）
  # 如果有 GitHub Releases，可以使用方式二
  depends_on "rust" => :build

  on_macos do
    # 从源码构建
    url "https://github.com/zevwings/workflow.rs.git", branch: "master"

    # 如果使用 GitHub Releases，可以这样配置：
    # if Hardware::CPU.intel?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/v0.1.0/workflow-0.1.0-x86_64-apple-darwin.tar.gz"
    #   sha256 "REPLACE_WITH_ACTUAL_SHA256"
    # end
    # if Hardware::CPU.arm?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/v0.1.0/workflow-0.1.0-aarch64-apple-darwin.tar.gz"
    #   sha256 "REPLACE_WITH_ACTUAL_SHA256"
    # end
  end

  def install
    system "cargo", "build", "--release", "--bin", "workflow", "--bin", "pr", "--bin", "qk"
    bin.install "target/release/workflow"
    bin.install "target/release/pr"
    bin.install "target/release/qk"
  end

  test do
    system "#{bin}/workflow", "--help"
    system "#{bin}/pr", "--help"
    system "#{bin}/qk", "--help"
  end
end

