//! 环境变量构建器
//!
//! 提供构建 shell 配置块内容的功能。

use color_eyre::Result;
use std::collections::HashMap;

use crate::core::shell::block;

/// 构建配置块
///
/// 根据环境变量构建配置块内容。
pub fn build_config_block(env_vars: &HashMap<String, String>) -> String {
    // 估算容量：标记行 + 注释行 + 每个环境变量行（key + value + 转义开销）
    let estimated_capacity = block::MARKER_START.len()
        + block::MARKER_END.len()
        + 200 // 注释行
        + env_vars.len() * 50; // 每个环境变量大约50字符

    let mut config_block = String::with_capacity(estimated_capacity);
    config_block.push_str(block::MARKER_START);
    config_block.push_str("\n# Generated by Workflow CLI - DO NOT edit manually\n");
    config_block
        .push_str("# These environment variables will be loaded when you start a new shell\n\n");

    // 按字母顺序排序键
    let mut keys: Vec<&String> = env_vars.keys().collect();
    keys.sort();

    for key in keys {
        let value = &env_vars[key];
        // 转义特殊字符
        let escaped_value = value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('$', "\\$")
            .replace('`', "\\`");
        // 使用 format! 宏，编译器会优化
        config_block.push_str(&format!("export {}=\"{}\"\n", key, escaped_value));
    }

    config_block.push('\n');
    config_block.push_str(block::MARKER_END);
    config_block.push('\n');

    config_block
}

/// 合并环境变量
pub fn merge_env_vars(
    existing: &HashMap<String, String>,
    new_vars: &HashMap<String, String>,
) -> HashMap<String, String> {
    let mut merged = existing.clone();
    merged.extend(new_vars.iter().map(|(k, v)| (k.clone(), v.clone())));
    merged
}

/// 构建配置内容
pub fn build_config_content(
    content_without_block: &str,
    env_vars: &HashMap<String, String>,
) -> Result<String> {
    // 如果没有环境变量，不创建配置块，直接返回原内容
    if env_vars.is_empty() {
        return Ok(content_without_block.to_string());
    }

    let config_block = build_config_block(env_vars);

    // 合并内容
    let final_content = if content_without_block.is_empty() {
        config_block
    } else if content_without_block.ends_with('\n') {
        format!("{}{}", content_without_block, config_block)
    } else {
        format!("{}\n{}", content_without_block, config_block)
    };

    Ok(final_content)
}
